"""empty message

Revision ID: 15185feb042d
Revises: ba077c767238
Create Date: 2022-12-07 19:35:43.037271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15185feb042d'
down_revision = 'ba077c767238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_3D',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('glb', sa.String(), nullable=True),
    sa.Column('stl', sa.String(), nullable=True),
    sa.Column('obj', sa.String(), nullable=True),
    sa.Column('_3ds', sa.String(), nullable=True),
    sa.Column('dae', sa.String(), nullable=True),
    sa.Column('skp', sa.String(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_3D')
    # ### end Alembic commands ###
