"""empty message

Revision ID: 7d0e8f0644ce
Revises: 98712c9caf74
Create Date: 2022-12-07 10:23:33.591383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0e8f0644ce'
down_revision = '98712c9caf74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.drop_column('post', 'img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('post', 'date_created')
    # ### end Alembic commands ###
