"""empty message

Revision ID: 7fde301bf81d
Revises: 15185feb042d
Create Date: 2022-12-12 10:54:53.249378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fde301bf81d'
down_revision = '15185feb042d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('glb', sa.String(), nullable=True))
    op.add_column('post', sa.Column('stl', sa.String(), nullable=True))
    op.add_column('post', sa.Column('obj', sa.String(), nullable=True))
    op.add_column('post', sa.Column('studio_max', sa.String(), nullable=True))
    op.add_column('post', sa.Column('dae', sa.String(), nullable=True))
    op.add_column('post', sa.Column('skp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'skp')
    op.drop_column('post', 'dae')
    op.drop_column('post', 'studio_max')
    op.drop_column('post', 'obj')
    op.drop_column('post', 'stl')
    op.drop_column('post', 'glb')
    # ### end Alembic commands ###
