"""empty message

Revision ID: ba077c767238
Revises: 7d0e8f0644ce
Create Date: 2022-12-07 10:32:36.086230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba077c767238'
down_revision = '7d0e8f0644ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.drop_column('post', 'img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('post', 'date_created')
    # ### end Alembic commands ###
